config/routes.rb
Rails.application.routes.draw do
  get 'applicants/index'
  get 'applicants/new'
  
  resources :companies, only: [:new, :edit, :update, :create]
  resources :positions
  resources :applicants, only: [:index, :new, :create]

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'home', to: 'home#index'
  root to: 'home#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :user
  belongs_to :position
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_one_attached :logo

  has_many :positions


  validates :name, presence: true
  validates :url, presence: true


end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :company

  enum career: [:developer, :business_intelligence, :information_technology, :design,
                :product_management, :other, :tecnology]
  enum contract: [:clt, :pg , :match]

  has_rich_text :description # Action Text para textos longos

  validates :name, :career, :contract, :city, :state, :summary, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :company
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!

  def new
    @company = current_user.build_company # Create a new company with associated user, but not yet saved. 
  end

  def edit
    @company = current_user.company
  end

  def create
    @company = current_user.build_company(company_params)
  
    if @company.save
      flash[:notice] = 'Empresa cadastrada com sucesso.'
      redirect_to root_path
    else
      flash[:error] = 'Erro ao cadastrar empresa.'
      render :new
    end
  end

  def update
    @company = current_user.company
    if @company.update(company_params)
      flash[:notice] = 'Empresa atualizada com sucesso.'
      redirect_to root_path
    else
      render :edit
    end
  end


  private

  def company_params
    params.require(:company).permit(:name, :url, :logo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_company, :set_i18n_careers, :set_i18n_contracts
  before_action :set_posotion, only: [:show, :edit, :update]
  def index
    @positions = @company.positions 
  end

  def new
    @positions = @company.positions.new
  end

  def create
    @positions = @company.positions.new(positions_params)
    if @positions.save
      flash[:notece] = 'Vaga cadastrada com sucesso.'
      redirect_to positions_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def show
  end

  private
  def positions_params
    params.require(:position).permit(:name, :career, :contract, :remote, :city, :state, :summary, :description, :publish)
  end
  def set_company
    redirect_to new_company_path if current_user.company.nil? #Redirect to new_company_path if the user doesn't have a company
    @company = current_user.company
  end

  def set_i18n_careers
    @careers = I18n.t('activerecord.attributes.position.careers')
  end

  def set_i18n_contracts
    @contracts = I18n.t('activerecord.attributes.position.contracts')
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def dynamic_url_company  # Define a URL dinâmica para a empresa do usuário atual
    if current_user&.company.present? && current_user.company.try(:id).present? # Verifica se o usuário tem uma empresa cadastrada e se ela tem um ID associado a ela 
      edit_company_path(current_user.company)
    else
      new_company_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/applicants/index.html.haml
%h1 Applicants#index
%p Find me in app/views/applicants/index.html.haml

app/views/applicants/new.html.haml
%h1 Applicants#new
%p Find me in app/views/applicants/new.html.haml

app/views/companies/_form.html.haml
= simple_form_for @company do |f|
  = f.error_notification
  = f.input :name
  = f.input :url
  = f.input :logo, as: :file

  - if @company.logo.attached?
    .image-preview
      = image_tag(@company.logo, alt: 'Logo atual')

  = f.button :submit, class: 'btn btn-primary btn-block', data: { turbo: false }

app/views/companies/edit.html.haml
%h2 Edite sua empresa - #{@company.name} 
= render 'form'

app/views/companies/new.html.haml
%h2 Minha Empresa 
= render 'form'

app/views/home/index.html.haml
%header.text-center
  %h1 Open Vagas
  %p Mural de vagas compartilhadas pela comunidade.


%form 
  .row 
    .col-sm   
      %label Carreira
      %input.form-control{:placeholder => "First name", :type => "text"}/  
    .col-sm
      %label Localização
      %input.form-control{:placeholder => "Last name", :type => "text",}/
    .col-sm
      %label Local de trabalho
      %input.form-control{:placeholder => "Last name", :type => "text"}/
    .col-sm
      %button.btn.btn-danger{:type => "submit", style: "margin-top: 24px"} Pesquisar

.card.card-position 
  .card-body
    .container.container-card
      .row 
        .col-2
          %img.img-fluid.rounded-circle{:src => "https://github.com/andradeveras.png", :alt => "Imagem de perfil"}
        .col-10
          %h4 Suporte de TI - Estagiário
          %h5 Desenvolvedor Web - Rio de Janeiro - RJ
          %p Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates deleniti quisquam odio esse natus voluptatem odit pariatur, consequatur blanditiis provident totam soluta aut quis? Debitis maiores nostrum distinctio voluptatum animi.
          .row 
            .col-sm.mt-3 
              %button.btn.btn-danger{:type => "button"} Ver mais
              %button.btn.btn-success{:type => "button"} Aplicar 
            .col-sm.text-right.mt-3.group-social-network 
              = link_to image_tag('social-network/whatsapp.svg', alt: 'Whatsapp'), '#'
              = link_to image_tag('social-network/linkedin.svg', alt: 'Linkedin'), '#'
              = link_to image_tag('social-network/twitter.svg', alt: 'Twitter'), '#'
              = link_to image_tag('social-network/copy.svg', alt: 'Copy', class: 'share-copy-icon'), '#'
              .card-body
    .container.container-card
      .row 
        .col-2
          %img.img-fluid.rounded-circle{:src => "https://github.com/andradeveras.png", :alt => "Imagem de perfil"}
        .col-10
          %h4 Suporte de TI - Estagiário
          %h5 Desenvolvedor Web - Rio de Janeiro - RJ
          %p Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptates deleniti quisquam odio esse natus voluptatem odit pariatur, consequatur blanditiis provident totam soluta aut quis? Debitis maiores nostrum distinctio voluptatum animi.
          .row 
            .col-sm.mt-3 
              %button.btn.btn-danger{:type => "button"} Ver mais
              %button.btn.btn-success{:type => "button"} Aplicar 
            .col-sm.text-right.mt-3.group-social-network 
              = link_to image_tag('social-network/whatsapp.svg', alt: 'Whatsapp'), '#'
              = link_to image_tag('social-network/linkedin.svg', alt: 'Linkedin'), '#'
              = link_to image_tag('social-network/twitter.svg', alt: 'Twitter'), '#'
              = link_to image_tag('social-network/copy.svg', alt: 'Copy', class: 'share-copy-icon'), '#'
      

%p.d-block.text-center.mt-3
  %a{:href => "#" } Paginação

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %title OpenVagas
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = render 'shared/topbar'
    %main.container
      = yield
    %footer
      %p Sistema desenvolvido por Leonardo Veras
      %p= Time.new.year

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %title OpenVagas
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload"
    = stylesheet_link_tag "devise", media: "all", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    #logreg-forms
      = yield

app/views/positions/_form.html.haml
= simple_form_for @positions do |f|
  = f.error_notification
  = f.input :name
  = f.input :career, as: :select, collection: @careers, label_method: :second, value_method: :first, include_blank: false, selected: @positions.career
  = f.input :contract, as: :select, collection: @contracts, label_method: :second, value_method: :first, include_blank: false, selected: @positions.contract
  = f.input :remote
  = f.input :publish
  = f.input :city
  = f.input :state
  = f.input :summary, maxlength: 360, input_html: { class: 'count-textarea', rows: 4 }
  #the-count
    %span#current 0
    %span#maximum / 360
  %label Descrição
  = f.rich_text_area :description
  = f.button :submit, class: 'btn btn-primary btn-block'

app/views/positions/edit.html.haml
%h1 Positions#edit
%p Find me in app/views/positions/edit.html.haml

app/views/positions/index.html.haml
Minhas Vagas

%table.table
  %thead.table-dark
    %tr
      %th{scope: "col"} Título
      %th{scope: "col"} Carreira
      %th{scope: "col"} Local
      %th{scope: "col"} Tipo de contrato
      %th{scope: "col"} Candidatura 
      %th{scope: "col"} Ações
  %tbody
    - @positions.each do |position|
      %tr
        %th{scope: "row"}= position.name 
        %td= position.career
        %td= position.remote # aplicar helper
        %td= position.contract 
        %td
          1(Ver detalhes)
        %td
          = link_to 'Editar', edit_position_path(position)

app/views/positions/new.html.haml
%h2 Criar uma vaga
= render 'form'

app/views/positions/show.html.haml
%h1 Positions#show
%p Find me in app/views/positions/show.html.haml

app/views/shared/_topbar.html.haml
%nav.navbar.navbar-expand-lg.fixed-top.navbar-dark.bg-dark{"aria-label" => "Main navigation"}
  .container-fluid
    %a.navbar-brand{href: "#"} Open Vagas
    %button#navbarSideCollapse.navbar-toggler.p-0.border-0{"aria-label" => "Toggle navigation", type: "button"}
      %span.navbar-toggler-icon
    #navbarsExampleDefault.navbar-collapse.offcanvas-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", href: root_path } Inicio
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", href: dynamic_url_company } Minha Empresa
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", href: positions_path } Minhas Vagas
        - unless user_signed_in? 
          %li.nav-item
            = link_to('Login/Cadastro', new_user_session_path, class: 'nav-link')
        - if user_signed_in?
          %li.nav-item.dropdown
            %a.dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "#"} Settings
            %ul.dropdown-menu
              = button_to('Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item', data: { turbo: false })
        %li.nav-item
          %a.nav-link.puclic_position{"aria-current" => "page", href: new_position_path } Publicar vaga 